services:
  - type: web
    name: asaliswad-ecommerce
    runtime: node
    plan: free
    rootDir: ecommerce-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NEXT_PUBLIC_SUPABASE_URL
        placeholder: "Your Supabase URL"
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        placeholder: "Your Supabase Anon Key"
